### PR TITLE
go: expose api errors

### PR DESCRIPTION
**Pull request by svix-frank**

### CODE REVIEW

**Review by tasn — APPROVED** [review]
Not proficient in Go, but it looks alright.

**Comment by tasn** [comment]
Actually

**Comment by tasn** [comment]
What's the "error" field? Is it `code` from the API? Or what?

The problem is that we have two kinds of errors, we have validation errors (422) and we have the HTTP errors (the rest) which are structured differently.

**Comment by svix-frank** [comment]
> What's the "error" field? Is it `code` from the API? Or what?

It's the display string for the error `422 Validation Error` or `409 Conflict`, not ideal.  The only way I can get the actual status code is to grab it from the resp object. =/

**Comment by tasn** [comment]
> > What's the "error" field? Is it `code` from the API? Or what?
> 
> It's the display string for the error `422 Validation Error` or `409 Conflict`, not ideal. The only way I can get the actual status code is to grab it from the resp object. =/

Ahhhh, cool. :)

**Pull request merged**
